### ISSUE TITLE
Modify should happen in-place

### ISSUE THREAD

**Issue by OwenArnold** [DMSC-Instrument-Data/instrument-prototype#15]
Currently `InstrumentTree::modify` does not change the `InstrumentTree` on which it is operating. This forces clients to have to remember to perform an reallocation/overwrites necessary. The purpose of this change is to make the `InstrumentTree::modify` work in-place. That will mean writing back to the `std::vector<Node>` member somehow. It will also make the `InstrumentTree` non-const.

**Comment by OwenArnold** [comment]
@SimonHeybrock. One consideration I've just had in making the `InstrumentTree` non-const is how it will behave in a multi-threaded scenario. At the moment, I think the thread safety would be pretty good, an invalid read type scenario can't happen because the modification is always a copy. Do you have any thoughts on this before I start?

**Comment by SimonHeybrock** [comment]
@OwenArnold We have to consider three cases:

1. Concurrent reads: Safe in both cases.

2. Reads concurrent with a write: Complicated, see below.

3. Concurrent writes: never safe (unless we manage to keep the `Node` vector, then writes to independent parts, e.g., changing the names of distinct components could in principle be safe).

Say we have two threads W (writer) and R (reader). Let us compare the current implementation, and the one discussed yesterday:

Current implementation:

- If both threads are owners of the instrument, W can write without disturbing R.
- If the master thread owns the instrument, reference count is > 1, and W and R only have a reference to the instrument, W will invalidate the reference R is holding.
- If the master thread owns the instrument, reference count is == 1, and W and R only have a reference to the instrument, W will invalidate the reference R is holding (instrument is always replaced).
- The `const` `InstrumentTree` will not protect from race conditions, i.e., it rarely makes sense to read while writing.

Proposed implementation:

- If both threads are owners of the instrument, W can write without disturbing R. The COW mechanism should take care of that as well.
- If the master thread owns the instrument, reference count is > 1, and W and R only have a reference to the instrument, W will **not invalidate** the reference R is holding. However, replacing the `Node` vector is a race condition.
- If the master thread owns the instrument, reference count is == 1, and W and R only have a reference to the instrument, W will **not invalidate** the reference R is holding. However, replacing the `Node` vector is a race condition.
- The `const` `InstrumentTree` will not protect from race conditions, i.e., it rarely makes sense to read while writing.

So, to me the second scenario looks a bit better, but in my opinion reading and writing simultaneously is always a bad idea.

**Comment by OwenArnold** [comment]
@SimonHeybrock. Thanks for putting all this down. It was the race condition around the `Node` vector that got me thinking about this. What I wanted to avoid was overuse of locks (and hence deadlocking) at a later stage because we hadn't thought about this kind of thing in the original design.

**Comment by SimonHeybrock** [comment]
@OwenArnold Looks will not help you with race conditions, in general. Look at the current `Instrument`, there are looks at a low level, but they will not help in any way if you move a bank while another thread is computing L2 values. The result will always be unpredictable and thus nonsensical. So in my opinion locks do not solve such problem and reads concurrent with writes should just be forbidden (apart from maybe specific cases).

**Comment by OwenArnold** [comment]
@SimonHeybrock. Agreed, the result will not make sense although you may succeed in keeping your references valid. 

Do you have a suggestion for how you would enforce/prevent reads concurrent with writes?

**Comment by SimonHeybrock** [comment]
@OwenArnold It has to be documented clearly that it is the resposibility of the client side to to this. I don't think there is any way reasonable of enforcing this. Basically what would be required, is to make **any* operation with the instrument **atomic**. That is:

- Locks around everything, also reads.
- No references to any internal data.

So basically all you can do is have getters that return (non-pointer types) by value (always making a deep copy), and setters.

**Comment by OwenArnold** [comment]
Fixed
